spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pwEhDgbGZSEvQaMVAUiUgxcnivYduhjY
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:49349/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
